# Generated by Django 5.2.8 on 2025-11-24 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='employee_images/')),
                ('face_encoding', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VisionTrack', max_length=150)),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='hero/')),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_link', models.CharField(max_length=200)),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_secondary_link', models.CharField(blank=True, max_length=200, null=True)),
                ('accuracy_rate', models.CharField(default='99.9%', max_length=20)),
                ('recognition_time', models.CharField(default='2s', max_length=20)),
                ('uptime', models.CharField(default='24/7', max_length=20)),
                ('footer_text', models.CharField(default='© 2024 VisionTrack. AI-Powered Face Attendance System.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
