# Generated by Django 5.2.8 on 2025-11-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
