# Generated by Django 5.2.8 on 2025-11-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0001_initial'),
        ('core', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_attendance', to='attendenceapp.attendancelog'),
        ),
    ]
